name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish application
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: minimalapi
          path: ./publish/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: minimalapi

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.staging.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.staging.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.staging.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure App Service
        run: |
          az webapp deploy \
            --resource-group Fares-staging-rg-01 \
            --name Fares-staging-app-01 \
            --src-path ./publish