deploy:
  runs-on: ubuntu-latest
  needs: build
  environment: staging
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: minimalapi

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure App Service
      run: |
        az webapp deploy \
          --resource-group Fares-staging-rg-01 \
          --name Fares-staging-app-01 \
          --src-path ./publish
